#!/bin/bash
set -euo pipefail

# Clean directories and files generated by Terraform

if [[ -d $PWD/terraform/hypervisor/.terraform  || -n "$(find $PWD/terraform/hypervisor -name 'terraform.tfstate*' -print -quit)" ]]; then
	rm -rf $PWD/terraform/hypervisor/.terraform*
	rm -f $PWD/terraform/hypervisor/terraform.tfstate*
fi
