apiVersion: cilium.io/v2alpha1
kind: CiliumNodeConfig
metadata:
  name: cilium-switch-from-iptables-ebpf
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  defaults:
    enable-bpf-masquerade: "true"
