apiVersion: v1 
data: 
  tls.crt: ${rancher_tls_additional_ca_crt_b64}
  tls.key: ${rancher_tls_key_b64}
kind: Secret 
metadata: 
  name: tls-rancher-bomar
  namespace: cattle-system 
type: kubernetes.io/tls 
--- 
apiVersion: v1 
data: 
  cacerts.pem: ${rancher_additional_ca_b64}
kind: Secret
metadata: 
  name: tls-ca 
  namespace: cattle-system
type: Opaque
